### ISSUE TITLE
CloudFormation Template instantiation FAILS

### ISSUE THREAD

**Issue by ksteward** [awslabs/ecs-mxnet-example#3]
I got the following errors when instantiating a Stack from the provided CloudFormation template.  I've captured the Events from just before the Failure until the final Events:

2017-07-06 | Status | Type | Logical ID | Status reason
-- | -- | -- | -- | --
23:54:58 UTC-0400DELETE_COMPLETEAWS::CloudFormation::Stackmxnet-ecs02-ECS-RHR2N38NG4U923:54:57 UTC-0400DELETE_COMPLETEAWS::EC2::SecurityGroupEcsSecurityGroup23:54:34 UTC-0400DELETE_COMPLETEAWS::IAM::RoleEC2Role23:54:33 UTC-0400DELETE_IN_PROGRESSAWS::IAM::RoleEC2Role23:54:31 UTC-0400DELETE_COMPLETEAWS::IAM::InstanceProfileEC2InstanceProfile23:54:31 UTC-0400DELETE_COMPLETEAWS::ECS::ClusterECSCluster23:54:31 UTC-0400DELETE_IN_PROGRESSAWS::EC2::SecurityGroupEcsSecurityGroup23:54:31 UTC-0400DELETE_IN_PROGRESSAWS::ECS::ClusterECSCluster23:54:31 UTC-0400DELETE_IN_PROGRESSAWS::IAM::InstanceProfileEC2InstanceProfile23:54:29 UTC-0400DELETE_COMPLETEAWS::AutoScaling::LaunchConfigurationContainerInstances23:54:29 UTC-0400DELETE_IN_PROGRESSAWS::AutoScaling::LaunchConfigurationContainerInstances23:54:27 UTC-0400DELETE_COMPLETEAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup23:54:09 UTC-0400DELETE_COMPLETEAWS::ElasticLoadBalancingV2::LoadBalancerECSALB23:54:08 UTC-0400DELETE_IN_PROGRESSAWS::ElasticLoadBalancingV2::LoadBalancerECSALB23:54:06 UTC-0400DELETE_COMPLETEAWS::ElasticLoadBalancingV2::TargetGroupECSTG23:54:06 UTC-0400DELETE_COMPLETEAWS::IAM::RoleECSServiceRole23:54:06 UTC-0400DELETE_COMPLETEAWS::ECR::RepositoryECRRepo23:54:05 UTC-0400DELETE_COMPLETEAWS::Logs::LogGroupCloudwatchLogsGroup23:54:05 UTC-0400DELETE_IN_PROGRESSAWS::ElasticLoadBalancingV2::TargetGroupECSTG23:54:05 UTC-0400DELETE_IN_PROGRESSAWS::Logs::LogGroupCloudwatchLogsGroup23:54:05 UTC-0400DELETE_IN_PROGRESSAWS::ECR::RepositoryECRRepo23:54:05 UTC-0400DELETE_IN_PROGRESSAWS::IAM::RoleECSServiceRole23:54:03 UTC-0400DELETE_COMPLETEAWS::ECS::TaskDefinitiontaskdefinition23:54:03 UTC-0400DELETE_COMPLETEAWS::ElasticLoadBalancingV2::ListenerALBListener23:54:02 UTC-0400DELETE_IN_PROGRESSAWS::ECS::TaskDefinitiontaskdefinition23:54:02 UTC-0400DELETE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerALBListener23:54:01 UTC-0400DELETE_COMPLETEAWS::ECS::Serviceservice23:53:31 UTC-0400DELETE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupHTTPinbound23:53:30 UTC-0400DELETE_COMPLETEAWS::IAM::RoleAutoscalingRole23:53:30 UTC-0400DELETE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupALBports23:53:30 UTC-0400DELETE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupSSHinbound23:53:29 UTC-0400DELETE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupHTTPinbound23:53:29 UTC-0400DELETE_COMPLETEAWS::ElasticLoadBalancingV2::ListenerRuleECSALBListenerRule23:53:29 UTC-0400DELETE_IN_PROGRESSAWS::ECS::Serviceservice23:53:28 UTC-0400DELETE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupALBports23:53:28 UTC-0400DELETE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerRuleECSALBListenerRule23:53:28 UTC-0400DELETE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupSSHinbound23:53:28 UTC-0400DELETE_IN_PROGRESSAWS::IAM::RoleAutoscalingRole23:53:28 UTC-0400DELETE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup23:53:26 UTC-0400DELETE_IN_PROGRESSAWS::CloudFormation::Stackmxnet-ecs02-ECS-RHR2N38NG4U9User Initiated23:52:38 UTC-0400CREATE_FAILEDAWS::CloudFormation::Stackmxnet-ecs02-ECS-RHR2N38NG4U9The following resource(s) failed to create: [service].23:52:34 UTC-0400CREATE_FAILEDAWS::ECS::ServiceserviceService arn:aws:ecs:us-east-1:175261584375:service/mxnet-ecs02-ECS-RHR2N38NG4U9-service-CA7NSLUVR84W did not stabilize.20:52:20 UTC-0400CREATE_COMPLETEAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup20:52:18 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroupReceived SUCCESS signal with UniqueId i-005ea41efa0465c0220:51:14 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroupResource creation Initiated20:51:13 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup |   | 23:54:58 UTC-0400 | DELETE_COMPLETE | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 |   |   | 23:54:57 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroup | EcsSecurityGroup |   |   | 23:54:34 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | EC2Role |   |   | 23:54:33 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | EC2Role |   |   | 23:54:31 UTC-0400 | DELETE_COMPLETE | AWS::IAM::InstanceProfile | EC2InstanceProfile |   |   | 23:54:31 UTC-0400 | DELETE_COMPLETE | AWS::ECS::Cluster | ECSCluster |   |   | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup |   |   | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster |   |   | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile |   |   | 23:54:29 UTC-0400 | DELETE_COMPLETE | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |   |   | 23:54:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |   |   | 23:54:27 UTC-0400 | DELETE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |   |   | 23:54:09 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |   |   | 23:54:08 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |   |   | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |   |   | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | ECSServiceRole |   |   | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::ECR::Repository | ECRRepo |   |   | 23:54:05 UTC-0400 | DELETE_COMPLETE | AWS::Logs::LogGroup | CloudwatchLogsGroup |   |   | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |   |   | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup |   |   | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo |   |   | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole |   |   | 23:54:03 UTC-0400 | DELETE_COMPLETE | AWS::ECS::TaskDefinition | taskdefinition |   |   | 23:54:03 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::Listener | ALBListener |   |   | 23:54:02 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition |   |   | 23:54:02 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener |   |   | 23:54:01 UTC-0400 | DELETE_COMPLETE | AWS::ECS::Service | service |   |   | 23:53:31 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |   |   | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | AutoscalingRole |   |   | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |   |   | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |   |   | 23:53:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |   |   | 23:53:29 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |   |   | 23:53:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::Service | service |   |   | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |   |   | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |   |   | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |   |   | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole |   |   | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |   |   | 23:53:26 UTC-0400 | DELETE_IN_PROGRESS | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 | User Initiated |   | 23:52:38 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 | The following resource(s) failed to create: [service]. |   | 23:52:34 UTC-0400 | CREATE_FAILED | AWS::ECS::Service | service | Service arn:aws:ecs:us-east-1:175261584375:service/mxnet-ecs02-ECS-RHR2N38NG4U9-service-CA7NSLUVR84W did not stabilize. |   | 20:52:20 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |   |   | 20:52:18 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Received SUCCESS signal with UniqueId i-005ea41efa0465c02 |   | 20:51:14 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Resource creation Initiated |   | 20:51:13 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup
  | 23:54:58 UTC-0400 | DELETE_COMPLETE | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 |  
  | 23:54:57 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroup | EcsSecurityGroup |  
  | 23:54:34 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | EC2Role |  
  | 23:54:33 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | EC2Role |  
  | 23:54:31 UTC-0400 | DELETE_COMPLETE | AWS::IAM::InstanceProfile | EC2InstanceProfile |  
  | 23:54:31 UTC-0400 | DELETE_COMPLETE | AWS::ECS::Cluster | ECSCluster |  
  | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup |  
  | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster |  
  | 23:54:31 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile |  
  | 23:54:29 UTC-0400 | DELETE_COMPLETE | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |  
  | 23:54:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |  
  | 23:54:27 UTC-0400 | DELETE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |  
  | 23:54:09 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |  
  | 23:54:08 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |  
  | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |  
  | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | ECSServiceRole |  
  | 23:54:06 UTC-0400 | DELETE_COMPLETE | AWS::ECR::Repository | ECRRepo |  
  | 23:54:05 UTC-0400 | DELETE_COMPLETE | AWS::Logs::LogGroup | CloudwatchLogsGroup |  
  | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |  
  | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup |  
  | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo |  
  | 23:54:05 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole |  
  | 23:54:03 UTC-0400 | DELETE_COMPLETE | AWS::ECS::TaskDefinition | taskdefinition |  
  | 23:54:03 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::Listener | ALBListener |  
  | 23:54:02 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition |  
  | 23:54:02 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener |  
  | 23:54:01 UTC-0400 | DELETE_COMPLETE | AWS::ECS::Service | service |  
  | 23:53:31 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |  
  | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::IAM::Role | AutoscalingRole |  
  | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |  
  | 23:53:30 UTC-0400 | DELETE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |  
  | 23:53:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |  
  | 23:53:29 UTC-0400 | DELETE_COMPLETE | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |  
  | 23:53:29 UTC-0400 | DELETE_IN_PROGRESS | AWS::ECS::Service | service |  
  | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |  
  | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |  
  | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |  
  | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole |  
  | 23:53:28 UTC-0400 | DELETE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |  
  | 23:53:26 UTC-0400 | DELETE_IN_PROGRESS | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 | User Initiated
  | 23:52:38 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | mxnet-ecs02-ECS-RHR2N38NG4U9 | The following resource(s) failed to create: [service].
  | 23:52:34 UTC-0400 | CREATE_FAILED | AWS::ECS::Service | service | Service arn:aws:ecs:us-east-1:175261584375:service/mxnet-ecs02-ECS-RHR2N38NG4U9-service-CA7NSLUVR84W did not stabilize.
  | 20:52:20 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |  
  | 20:52:18 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Received SUCCESS signal with UniqueId i-005ea41efa0465c02
  | 20:51:14 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Resource creation Initiated
  | 20:51:13 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup

**Comment by ghost** [comment]
update should fix it
