### ISSUE TITLE
ECS Cfn never finishes

### ISSUE THREAD

**Issue by ksteward** [awslabs/ecs-mxnet-example#4]
the ECS Cfn (https://s3.amazonaws.com/mxnet-template-cicd-feb27/ecs-template.yaml) doesn't fail but also never finishes:  CREATE_IN_PROGRESS continues to show even after 2hr.  Thus the master Cfn doesn't finish (also shows CREATE_IN_PROGRESS) and no MLServiceUrl Output is ever reported.  Unable to test the prediction service.  Below is the progress that the ECS Cfn reports:

2017-07-12 | Status | Type | Logical ID | Status reason
-- | -- | -- | -- | --
15:39:05 UTC-0400CREATE_COMPLETEAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup15:39:04 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroupReceived SUCCESS signal with UniqueId i-0111957d0a111b53315:38:01 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroupResource creation Initiated15:38:00 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::AutoScalingGroupECSAutoScalingGroup15:37:57 UTC-0400CREATE_COMPLETEAWS::AutoScaling::LaunchConfigurationContainerInstances15:37:57 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::LaunchConfigurationContainerInstancesResource creation Initiated15:37:56 UTC-0400CREATE_IN_PROGRESSAWS::AutoScaling::LaunchConfigurationContainerInstances15:37:52 UTC-0400CREATE_COMPLETEAWS::IAM::InstanceProfileEC2InstanceProfile15:37:21 UTC-0400CREATE_COMPLETEAWS::ElasticLoadBalancingV2::ListenerRuleECSALBListenerRule15:37:21 UTC-0400CREATE_IN_PROGRESSAWS::ECS::ServiceserviceResource creation Initiated15:37:20 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerRuleECSALBListenerRuleResource creation Initiated15:37:20 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerRuleECSALBListenerRule15:37:19 UTC-0400CREATE_IN_PROGRESSAWS::ECS::Serviceservice15:37:16 UTC-0400CREATE_COMPLETEAWS::ElasticLoadBalancingV2::ListenerALBListener15:37:16 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerALBListenerResource creation Initiated15:37:15 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::ListenerALBListener15:37:12 UTC-0400CREATE_COMPLETEAWS::ElasticLoadBalancingV2::TargetGroupECSTG15:37:11 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::TargetGroupECSTGResource creation Initiated15:37:10 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::TargetGroupECSTG15:37:08 UTC-0400CREATE_COMPLETEAWS::ElasticLoadBalancingV2::LoadBalancerECSALB15:35:51 UTC-0400CREATE_IN_PROGRESSAWS::IAM::InstanceProfileEC2InstanceProfileResource creation Initiated15:35:51 UTC-0400CREATE_IN_PROGRESSAWS::IAM::InstanceProfileEC2InstanceProfile15:35:47 UTC-0400CREATE_COMPLETEAWS::IAM::RoleEC2Role15:35:34 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleEC2RoleResource creation Initiated15:35:23 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleEC2Role15:34:45 UTC-0400CREATE_COMPLETEAWS::IAM::RoleECSServiceRole15:34:43 UTC-0400CREATE_COMPLETEAWS::IAM::RoleAutoscalingRole15:34:39 UTC-0400CREATE_COMPLETEAWS::ECS::TaskDefinitiontaskdefinition15:34:38 UTC-0400CREATE_IN_PROGRESSAWS::ECS::TaskDefinitiontaskdefinitionResource creation Initiated15:34:38 UTC-0400CREATE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupHTTPinbound15:34:37 UTC-0400CREATE_IN_PROGRESSAWS::ECS::TaskDefinitiontaskdefinition15:34:37 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupHTTPinboundResource creation Initiated15:34:35 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::LoadBalancerECSALBResource creation Initiated15:34:34 UTC-0400CREATE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupSSHinbound15:34:34 UTC-0400CREATE_COMPLETEAWS::EC2::SecurityGroupIngressEcsSecurityGroupALBports15:34:33 UTC-0400CREATE_COMPLETEAWS::Logs::LogGroupCloudwatchLogsGroup15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupSSHinboundResource creation Initiated15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupSSHinbound15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupALBportsResource creation Initiated15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::ElasticLoadBalancingV2::LoadBalancerECSALB15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::Logs::LogGroupCloudwatchLogsGroupResource creation Initiated15:34:33 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupALBports15:34:32 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupIngressEcsSecurityGroupHTTPinbound15:34:32 UTC-0400CREATE_COMPLETEAWS::ECR::RepositoryECRRepo15:34:32 UTC-0400CREATE_IN_PROGRESSAWS::Logs::LogGroupCloudwatchLogsGroup15:34:32 UTC-0400CREATE_IN_PROGRESSAWS::ECR::RepositoryECRRepoResource creation Initiated15:34:31 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleAutoscalingRoleResource creation Initiated15:34:31 UTC-0400CREATE_COMPLETEAWS::ECS::ClusterECSCluster15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::ECR::RepositoryECRRepo15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::ECS::ClusterECSClusterResource creation Initiated15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleECSServiceRoleResource creation Initiated15:34:30 UTC-0400CREATE_COMPLETEAWS::EC2::SecurityGroupEcsSecurityGroup15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleAutoscalingRole15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::ECS::ClusterECSCluster15:34:30 UTC-0400CREATE_IN_PROGRESSAWS::IAM::RoleECSServiceRole15:34:29 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupEcsSecurityGroupResource creation Initiated15:34:29 UTC-0400CREATE_IN_PROGRESSAWS::EC2::SecurityGroupEcsSecurityGroup15:34:22 UTC-0400CREATE_IN_PROGRESSAWS::CloudFormation::Stackecs-mxnet-image-predict-ECS-LJ2PWCROX0VVUser InitiatedPhysical ID:arn:aws:cloudformation:us-east-1:175261584375:stack/ecs-mxnet-image-predict-ECS-LJ2PWCROX0VV/1b05ef20-6739-11e7-a567-500c286e1a36 |   | 15:39:05 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |   |   | 15:39:04 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Received SUCCESS signal with UniqueId i-0111957d0a111b533 |   | 15:38:01 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Resource creation Initiated |   | 15:38:00 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |   |   | 15:37:57 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |   |   | 15:37:57 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances | Resource creation Initiated |   | 15:37:56 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |   |   | 15:37:52 UTC-0400 | CREATE_COMPLETE | AWS::IAM::InstanceProfile | EC2InstanceProfile |   |   | 15:37:21 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |   |   | 15:37:21 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Service | service | Resource creation Initiated |   | 15:37:20 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule | Resource creation Initiated |   | 15:37:20 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |   |   | 15:37:19 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Service | service |   |   | 15:37:16 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::Listener | ALBListener |   |   | 15:37:16 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener | Resource creation Initiated |   | 15:37:15 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener |   |   | 15:37:12 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |   |   | 15:37:11 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG | Resource creation Initiated |   | 15:37:10 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |   |   | 15:37:08 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |   |   | 15:35:51 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile | Resource creation Initiated |   | 15:35:51 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile |   |   | 15:35:47 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | EC2Role |   |   | 15:35:34 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | EC2Role | Resource creation Initiated |   | 15:35:23 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | EC2Role |   |   | 15:34:45 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | ECSServiceRole |   |   | 15:34:43 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | AutoscalingRole |   |   | 15:34:39 UTC-0400 | CREATE_COMPLETE | AWS::ECS::TaskDefinition | taskdefinition |   |   | 15:34:38 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition | Resource creation Initiated |   | 15:34:38 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |   |   | 15:34:37 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition |   |   | 15:34:37 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound | Resource creation Initiated |   | 15:34:35 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB | Resource creation Initiated |   | 15:34:34 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |   |   | 15:34:34 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |   |   | 15:34:33 UTC-0400 | CREATE_COMPLETE | AWS::Logs::LogGroup | CloudwatchLogsGroup |   |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound | Resource creation Initiated |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |   |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports | Resource creation Initiated |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |   |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup | Resource creation Initiated |   | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |   |   | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |   |   | 15:34:32 UTC-0400 | CREATE_COMPLETE | AWS::ECR::Repository | ECRRepo |   |   | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup |   |   | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo | Resource creation Initiated |   | 15:34:31 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole | Resource creation Initiated |   | 15:34:31 UTC-0400 | CREATE_COMPLETE | AWS::ECS::Cluster | ECSCluster |   |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo |   |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster | Resource creation Initiated |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole | Resource creation Initiated |   | 15:34:30 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroup | EcsSecurityGroup |   |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole |   |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster |   |   | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole |   |   | 15:34:29 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup | Resource creation Initiated |   | 15:34:29 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup |   |   | 15:34:22 UTC-0400 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | ecs-mxnet-image-predict-ECS-LJ2PWCROX0VV | User Initiated |   | Physical ID:arn:aws:cloudformation:us-east-1:175261584375:stack/ecs-mxnet-image-predict-ECS-LJ2PWCROX0VV/1b05ef20-6739-11e7-a567-500c286e1a36
  | 15:39:05 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |  
  | 15:39:04 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Received SUCCESS signal with UniqueId i-0111957d0a111b533
  | 15:38:01 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup | Resource creation Initiated
  | 15:38:00 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | ECSAutoScalingGroup |  
  | 15:37:57 UTC-0400 | CREATE_COMPLETE | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |  
  | 15:37:57 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances | Resource creation Initiated
  | 15:37:56 UTC-0400 | CREATE_IN_PROGRESS | AWS::AutoScaling::LaunchConfiguration | ContainerInstances |  
  | 15:37:52 UTC-0400 | CREATE_COMPLETE | AWS::IAM::InstanceProfile | EC2InstanceProfile |  
  | 15:37:21 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |  
  | 15:37:21 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Service | service | Resource creation Initiated
  | 15:37:20 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule | Resource creation Initiated
  | 15:37:20 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerRule | ECSALBListenerRule |  
  | 15:37:19 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Service | service |  
  | 15:37:16 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::Listener | ALBListener |  
  | 15:37:16 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener | Resource creation Initiated
  | 15:37:15 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | ALBListener |  
  | 15:37:12 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |  
  | 15:37:11 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG | Resource creation Initiated
  | 15:37:10 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::TargetGroup | ECSTG |  
  | 15:37:08 UTC-0400 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |  
  | 15:35:51 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile | Resource creation Initiated
  | 15:35:51 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::InstanceProfile | EC2InstanceProfile |  
  | 15:35:47 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | EC2Role |  
  | 15:35:34 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | EC2Role | Resource creation Initiated
  | 15:35:23 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | EC2Role |  
  | 15:34:45 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | ECSServiceRole |  
  | 15:34:43 UTC-0400 | CREATE_COMPLETE | AWS::IAM::Role | AutoscalingRole |  
  | 15:34:39 UTC-0400 | CREATE_COMPLETE | AWS::ECS::TaskDefinition | taskdefinition |  
  | 15:34:38 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition | Resource creation Initiated
  | 15:34:38 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |  
  | 15:34:37 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::TaskDefinition | taskdefinition |  
  | 15:34:37 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound | Resource creation Initiated
  | 15:34:35 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB | Resource creation Initiated
  | 15:34:34 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |  
  | 15:34:34 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |  
  | 15:34:33 UTC-0400 | CREATE_COMPLETE | AWS::Logs::LogGroup | CloudwatchLogsGroup |  
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound | Resource creation Initiated
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupSSHinbound |  
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports | Resource creation Initiated
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::LoadBalancer | ECSALB |  
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup | Resource creation Initiated
  | 15:34:33 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupALBports |  
  | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroupIngress | EcsSecurityGroupHTTPinbound |  
  | 15:34:32 UTC-0400 | CREATE_COMPLETE | AWS::ECR::Repository | ECRRepo |  
  | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::Logs::LogGroup | CloudwatchLogsGroup |  
  | 15:34:32 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo | Resource creation Initiated
  | 15:34:31 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole | Resource creation Initiated
  | 15:34:31 UTC-0400 | CREATE_COMPLETE | AWS::ECS::Cluster | ECSCluster |  
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECR::Repository | ECRRepo |  
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster | Resource creation Initiated
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole | Resource creation Initiated
  | 15:34:30 UTC-0400 | CREATE_COMPLETE | AWS::EC2::SecurityGroup | EcsSecurityGroup |  
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | AutoscalingRole |  
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::ECS::Cluster | ECSCluster |  
  | 15:34:30 UTC-0400 | CREATE_IN_PROGRESS | AWS::IAM::Role | ECSServiceRole |  
  | 15:34:29 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup | Resource creation Initiated
  | 15:34:29 UTC-0400 | CREATE_IN_PROGRESS | AWS::EC2::SecurityGroup | EcsSecurityGroup |  
  | 15:34:22 UTC-0400 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | ecs-mxnet-image-predict-ECS-LJ2PWCROX0VV | User Initiated
  | Physical ID:arn:aws:cloudformation:us-east-1:175261584375:stack/ecs-mxnet-image-predict-ECS-LJ2PWCROX0VV/1b05ef20-6739-11e7-a567-500c286e1a36

**Comment by ghost** [comment]
update should have fixed it
